language: node_js
node_js:
- '4'
before_script:
- npm install -g gulp-cli bower
- bower install
script: gulp build
after_success:
- bash ./travis/deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: a34174b2f5c2
  - COMMIT_AUTHOR_EMAIL: diogo@stormsys.net
before_install:
- openssl aes-256-cbc -K $encrypted_92283b7563b5_key -iv $encrypted_92283b7563b5_iv
  -in travis/deploy_key.enc -out travis/deploy_key -d
